#Database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/AdvertisingCompanies
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect

  #flyway
flyway:
  url: jdbc:postgresql://localhost:5432/AdvertisingCompanies
  user: postgres
  password: 1234
  schemas: public
  locations: filesystem:db/migration
